name: sqlserver-mcp-npm

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  PATH_PROJECT_FILE: ./sql-ai/MssqlMcp/Node/package.json
  PATH_PROJECT: ./sql-ai/MssqlMcp/Node
  SQLSERVER_MCP_REPO: https://github.com/Azure-Samples/SQL-AI-samples.git
  NPM_REGISTRY: https://registry.npmjs.org/

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: ${{ env.NPM_REGISTRY }}

      - name: Clonar repositorio com o MCP Server do SQL Server
        run: git clone ${{ env.SQLSERVER_MCP_REPO }} sql-ai

      - name: Exibir conteudos do repositorio clonado
        run: |
          pwd
          ls -l
          echo
          echo
          cd sql-ai
          pwd
          ls -l
          echo
          echo
          cd MssqlMcp/Node
          pwd
          ls -l

      - name: Exibir conteudo do arquivo package.json antes das alteracoes
        run: cat ${{ env.PATH_PROJECT_FILE }}

      - name: Alterar name e adicionar publishConfig no package.json
        run: |
          cd ${{ env.PATH_PROJECT }}
          jq '.name = "mssql-mcp-server-2025-08-a" | .publishConfig = {"access":"public"}' package.json > package.tmp.json
          mv package.tmp.json package.json

      - name: Exibir conteudo do arquivo package.json apos as alteracoes
        run: cat ${{ env.PATH_PROJECT_FILE }}

      - name: Instalar dependencias (ci = clean install)
        run: |
          cd ${{ env.PATH_PROJECT }}
          npm ci

      - name: Publicar no npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          cd ${{ env.PATH_PROJECT }}
          npm publish --access public

      # - name: Build do package
      #   run: |
      #     cd ${{ env.PATH_PROJECT }}
      #     if [ -f package.json ] && grep -q '"build"' package.json; then
      #       npm run build
      #     fi

      # - name: Exibir arquivos gerados após build
      #   run: |
      #     cd ${{ env.PATH_PROJECT }}/dist
      #     pwd
      #     echo
      #     echo
      #     ls -l